# Generated by Django 4.2.5 on 2024-05-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='Status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
