# Generated by Django 4.2.5 on 2024-05-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='Status',
            field=models.CharField(blank=True, default='pending', max_length=250),
        ),
    ]
