# Generated by Django 4.2.5 on 2024-05-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='seller_message',
            field=models.TextField(blank=True),
        ),
    ]
